version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_DB: "vuln"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d vuln"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: "pguser"
      PGPASSWORD: "pgpassword"
      PGDATABASE: "vuln"
      PGPORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: ["sh", "-c", "node ./server.js"]
    stdin_open: false
    tty: false

volumes:
  db_data: